### ISSUE TITLE
Test browserify on reqlite

### ISSUE THREAD

**Issue by neumino** [neumino/reqlite#16]
See what breaks.
`Buffer` may break?

**Comment by rclai** [comment]
It would be nice to get reqlite working 100% in the browser for use with Meteor! :smiley: 
 Is there any way to help?

**Comment by neumino** [comment]
I think @Slava ran it on the previous version. I personally havent tried.

Feel free to give a shot and fix what's needed :)

**Comment by rclai** [comment]
I will try, it is a very complex piece of work :smiley:.

**Comment by neumino** [comment]
Reporting the errors would already help :)

**Comment by neumino** [comment]
One issue mentionned by @rclai in #27:

```js
r.table('cities').orderBy(r.desc('population')).run()
```

```
reql-client-errors.js:28 Uncaught TypeError: Cannot read property 'slice' of undefined
message: "Cannot read property 'slice' of undefined"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: ErrorRqlServerError @ reql-client-errors.js:28
RqlRuntimeError @ reql-client-errors.js:51
mkErr @ rethink-client-utils.js:20
_runQuery @ rethink-client.js:192
runReqliteQuery @ rethink-client.js:176
(anonymous function) @ rethink-client.js:231
(anonymous function) @ VM1677:2
InjectedScript._evaluateOn @ VM1562:883
InjectedScript._evaluateAndWrap @ VM1562:816
InjectedScript.evaluate @ VM1562:682
```

**Comment by neumino** [comment]
I fixed the dependencies in https://github.com/neumino/reqlite/issues/17, so it has more chance to properly work now :)

**Comment by rclai** [comment]
Okay, I will try this out.

**Comment by rclai** [comment]
Are you supposed to be able to just create a browserify file like this:

```js
reqlite = require('reqlite');
module.exports = reqlite;
```

And it work?

I get this error on the browser:
```
Uncaught Error: Cannot find module '/node_modules/reqlite/lib/protodef.js'
```

[Here's a repro](https://github.com/rclai/reqlite-browserify-issue).

**Comment by neumino** [comment]
Hum, I have used browserify a long time ago and don't really remember.

It should ouput a file like `reqlite.js` that you can import in a `script` tag if I'm not mistaken.
Then you can run queries doing something like
```
var Server = new Server();
var query = r.db('foo').table('bar').filter({id: 1})
var reqliteQuery = new Query(server, query.build(), {})
var result = reqliteQuery.evaluate(query, {})
console.log(result)
```

**Comment by rclai** [comment]
Right, exactly, but when I tried browserifying Reqlite, it couldn't get the `protodef.js` modules. Did you check out the reproduction I linked you to?

**Comment by neumino** [comment]
Hum, I just took a quick look.

It looks like browserify doesn't like `__dirname`.
Typically this solve the problem:
```
sed -i 's/__dirname+"\//"\.\//g' lib/*
sed -i 's/__dirname+"\//"\.\//g' lib/util/*
```
There might be an option in browserify to avoid running this sed command (and I would be surprised if there isn't)

Then this worked for me
```
browserify -e lib/index.js -s reqlite -o reqlite.js
```

The problem is that `net.createServer` doesn't exist, and reqlite will throw.

**Comment by threepointone** [comment]
I managed get this to somewhat "work" over the last couple of days (ongoing work in this [branch](https://github.com/threepointone/reqlite/tree/browser)). Some notes -

- replaced `request` with `superagent` - it's easier to make work across node/browser, and is *much* lighter by weight. 
- updated `geographiclib` manually 
- `process.stderr = { write: ::console.log };`
- wrote simplistic polyfills for the `net` package - this lets us simulate the server/sockets
- make a webpack build that pulls in rethinkdb, reqlite, the shims etc, which __then__ in turn is consumed by other js files. 
- 160k bundle gzipped
- would have been much easier if rethinkdb/4316 just worked 
- I'll next work on - run matching tests in browser / node 

I'll remove the babel dependency, and shuffle around the files, but in general, does the approach work? If so, I'll start a PR later today.

**Comment by neumino** [comment]
@threepointone -- can you open a pull request to take a look at the changes?
Nice work too!

**Comment by threepointone** [comment]
Opened PR #52 cheers!

**Comment by neumino** [comment]
Ok, so I eventually fixed the circular dependency, and I believe browserify properly bundle things now.
There's a script `browserify.js` in the `browserify` branch.

The things left to do are:
- Add a way to create a Server without `net`
- Refactor some stuff in `connection.js` to bypass all the buffer parsing/decoding.

**Comment by neumino** [comment]
I got `reqlite` to work in the browser (using `browserify`).

It now works with `rethinkdbdash` (not the official driver yet) as `reqlite` just creates a fake tcp connection that the driver needs to wrap. That's done by passing the field `connection` in the options of `r.connect` and using this connection instead of creating a new one with `net.connect`.
@deontologician -- any chance you could do the same in the official driver?

It needs a bit more testing, and some polishing (I think closing a connection doesn't work perfectly - they are not GC I think), but the main thing works :)

**Comment by neumino** [comment]
Done in 2.2.2
