### ISSUE TITLE
Browser: r.desc error

### ISSUE THREAD

**Issue by rclai** [neumino/reqlite#27]
Here's one. Is there a specific way you'd like me to title these issues?

```js
r.table('cities').orderBy(r.desc('population')).run()
```
```
reql-client-errors.js:28 Uncaught TypeError: Cannot read property 'slice' of undefined
message: "Cannot read property 'slice' of undefined"
stack: (...)
get stack: function () { [native code] }
set stack: function () { [native code] }
__proto__: ErrorRqlServerError @ reql-client-errors.js:28
RqlRuntimeError @ reql-client-errors.js:51
mkErr @ rethink-client-utils.js:20
_runQuery @ rethink-client.js:192
runReqliteQuery @ rethink-client.js:176
(anonymous function) @ rethink-client.js:231
(anonymous function) @ VM1677:2
InjectedScript._evaluateOn @ VM1562:883
InjectedScript._evaluateAndWrap @ VM1562:816
InjectedScript.evaluate @ VM1562:682
```

**Comment by neumino** [comment]
Let's try to keep everything in the same thread.
Could you post some instructions on how you ran browserify too?
Thanks!

**Comment by rclai** [comment]
Well, I was using @Slava's Meteor package, so essentially he did it like [this](https://github.com/Slava/meteor-rethinkdb/blob/master/driver-source/build.sh#L27-L30).

**Comment by rclai** [comment]
Oh wait, did you mean to keep it in [this thread](https://github.com/neumino/reqlite/issues/16)?

**Comment by neumino** [comment]
Yes, let's try to keep everything there:
https://github.com/neumino/reqlite/issues/16

It will make easier to know what's missing for browserify.
