### ISSUE TITLE
Use container for Travis

### ISSUE THREAD

**Issue by neumino** [neumino/reqlite#28]
Travis is pretty slow (to be more precise it's slow to boot the machine/vm/whatever they use)

We can create containers. This require us to not use `sudo`, and therefore build rethinkdb ourselves (or download a binary).

**Comment by zephraph** [comment]
How will using a container speed up the test?

**Comment by neumino** [comment]
http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

Faster boot basically.

**Comment by neumino** [comment]
Done in 2.2.4
