### ISSUE TITLE
feature request: option to disable out output

### ISSUE THREAD

**Issue by joeybaker** [neumino/reqlite#34]
I'm loving reqlite for testing, but all the output isn't really necessary in a test. An option to turn it all off would be appreciated.

**Comment by neumino** [comment]
Make sense.
I'll add a constant later and refactor a bit things to make these settings be changed by passing a flag to Server.

**Comment by neumino** [comment]
Available via `--silent` or in `constants.js`

**Comment by joeybaker** [comment]
@neumino would you mind doing an npm release with this in it?

**Comment by neumino** [comment]
@joeybaker -- sorry about that, it's released in 2.0.3

**Comment by joeybaker** [comment]
Thanks!
