### ISSUE TITLE
Could I use Thinky.js with reqlite instead of a connection option ? 

### ISSUE THREAD

**Issue by freak4pc** [neumino/reqlite#40]
Something like 

```
let reqlite = require('reqlite'),
     thinky = require('thinky')(reqlite)
```

**Comment by neumino** [comment]
Yes and no.

If you start reqlite with `./bin/reqlite`, reqlite will behave like a rethinkdb server, so in this case it works.

You cannot do `thinky = require('thinky')(reqlite)` because reqlite doesn't provide a (public) API to send queries directly to the server without running a tcp server first.

**Comment by freak4pc** [comment]
Alright, so - trying to understand... 
Why would I even need reqlite instead of just running another instance of RethinkDB? 
Just for in-memory usage? 

I thought of using this for testing. I guess I could add reqlite as a dev dependency and have my test script run reqlite before running the tests. Should that work?

**Comment by neumino** [comment]
The point of reqlite *at the moment* is:
- For test, it's easier to spin up reqlite than rethinkdb: For example reqlite runs on Windows, doesn't require rights to access the filesystem etc.
- For front-end developers, it's a way to execute queries in the browsers and then sync things (like Meteor).

In the longer term, it would be cool for testing purposes to be able to do:
```
var reqlite = require('reqlite');
var server = new reqlite();
var connection = server.createConnection();

// optional
// connection.mockResponse(...) // mock the next response

query.run(connection).then(...)
```
This requires a little more work though.

**Comment by freak4pc** [comment]
I've now completely moved my tests to use reqlite and redis-js so it should be completely independent of the system. 

I've wanted to share my REQLite workflow with anyone who might want to do the same. Until reqlite can run independently inside Node.js, this is the script I wrote as a pre-test hook in my package.json file. It checks whether or not Reqlite is installed, if not - installs it and then my test scripts are using 28016 instead of 28015 for tests. Works very smoothly so far :) 

Here's how it looks: 
![NPM Test with REQLite](http://g.recordit.co/BD2QUl5yzQ.gif)

```javascript
'use strict'

let	exec 	= require('child_process').exec,
	spawn 	= require('child_process').spawn,
	colors 	= require('colors')

let child 	= exec('npm list -g reqlite >& /dev/null', (err, stdout, stderr) => {
	let startR = () => {
							console.log("> " + "Starting REQLite...".magenta)

							exec('pkill -f "reqlite"', (err, stdout, stderr) => {
								let reqlite = spawn('reqlite', ['--port-offset', '1'], {detached: true})
							
								reqlite.stderr.on('data', function (data) {
									console.log("> " + "REQLite is running...".green)
									process.exit(0)							  
								});

								reqlite.on('exit', function (code) {
								  console.log('child process exited with code ' + code);
								});
							})
						}

	if(err) {
		if (err.code == 1){
			// Should install
			console.log("> " + "Installing REQLite...".magenta)

			let install = exec('npm install -g reqlite', (err, stdout, stderr) => {
				console.log("> " + "Done installing REQLite".green)
				console.log(" ")
				startR()

			})
		}else{
			throw err
		}
	}else{
		console.log("> " + "REQLite is already installed".cyan)
		startR()
	}
})
```

**Comment by Lemmmy** [comment]
Are there any alternative ways to do this in 2018, or do we still have to find a way to manage a `bin/reqlite` process?
