### ISSUE TITLE
String.split() cannot be chained

### ISSUE THREAD

**Issue by AusIV** [neumino/reqlite#43]
Recently I've been trying to do some basic string manipulation in queries, and running my tests against reqlite. If I do:

    r.expr("a b c d").split().run().then(console.log)

I get `["a", "b", "c", "d"]` as expected. But if I do:

        r.expr("a b c d").split().count().run().then(console.log)

I never get a callback. Likewise for other operations I've tried like map and reduce. I'm using rethinkdbdash as the driver, but this works against a real RethinkDB instance, so I'm sure it's not a driver issue.

**Comment by neumino** [comment]
Found the bug and have a fix for that.
It's a bit annoying that 2.1 is actually not compatible with 2.0. I have tons of tests failing because of different error messages

**Comment by neumino** [comment]
Thanks @AusIV for the report. It should be fixed in 2.0.5
