### ISSUE TITLE
No Callback for Grouping and Mapping

### ISSUE THREAD

**Issue by AusIV** [neumino/reqlite#45]
I've discovered that calling .map() on grouped items fails with no callback.

Example:

    it('group - 23', function(done) {
      var query = r.expr([
        {id: 1, x: 3},
        {id: 1, x: 4},
        {id: 2, x: 5},
        {id: 3, x: 6}
      ]).group("id").map(function(item){return 2}).ungroup().orderBy("group");
      compare(query, done);
    });

I have a patch to add the test, but haven't found my way around well enough to do anything about it:

https://github.com/neumino/reqlite/compare/master...AusIV:bugfix/group-map

**Comment by neumino** [comment]
Thanks for the report.
Fixed in 2.0.6
