### ISSUE TITLE
why use a copied version of geographiclib.js?

### ISSUE THREAD

**Issue by threepointone** [neumino/reqlite#50]
I ask because it seems to have a bunch no-undef bugs, that seem to be fixed https://github.com/39dotyt/node-geographiclib could you use the npm version instead? or are there local modifications?

**Comment by neumino** [comment]
Hum, I believe it's because I didn't find the node package before. Feel free to add it in package.json

**Comment by threepointone** [comment]
I'll make a PR today

**Comment by threepointone** [comment]
Opened PR #51

**Comment by neumino** [comment]
PR merged, thanks @threepointone

**Comment by neumino** [comment]
Release in 2.1.2 too.
