### ISSUE TITLE
Way to stop server with node API?

### ISSUE THREAD

**Issue by yamalight** [neumino/reqlite#65]
Is there a way to stop reqlite server after creating it using node API? 
Running server keeps my tests up forever (due to network event listeners).
I would want something like this:
```js
// init dummy server
const server = new Reqlite({silent: true});
const connection = server.createConnection();
// tests go here
....
// terminate server once done
server.close();
```

If it does not exist, I would be willing to implement and create a PR if you are OK with that addition.

**Comment by neumino** [comment]
It I'm not mistaken, it doesn't exist. A PR would be welcome :)

You have to stop listening on the server, and also close all the connections.

**Comment by yamalight** [comment]
@neumino alright, cool. then I'll prepare the PR

**Comment by yamalight** [comment]
@neumino is there a way to tell that all operations are done? closing during the operations kinda breaks things :)

**Comment by neumino** [comment]
Hum, I don't think so. In the first iteration, you don't have to immediately abort the queries.
You can just close the connection, and if we try to write on them after the server is closed, you can just skip the operation.

**Comment by yamalight** [comment]
@neumino just create a PR, please have a look and let me know if something needs to be changed
