### ISSUE TITLE
Support new handshake for 2.3

### ISSUE THREAD

**Issue by neumino** [neumino/reqlite#79]
RethinkDB 2.3 introduced a new handshake (to support authentification).
Reqlite currently doesn't support it or implement any of the ACL.

**Comment by simonratner** [comment]
Oh, this means I can't move up to rethinkdbdash/thinky 2.3 😭

**Comment by neumino** [comment]
Ah, I totally forgot about that. I'll update reqlite to the new handshake. It may not support passwords in a first time though.

**Comment by neumino** [comment]
Just release 2.3.0 with the new handshake.
