### ISSUE TITLE
How do you run this as a process?

### ISSUE THREAD

**Issue by chrisabrams** [neumino/reqlite#82]
I've tried using this with something such as `forever`, or even simply using `exec`/`spawn`, but it always leads to the `reqlite` process shutting down:

```
forever start `which reqlite`

cat `path to forever log`

info: Server got SIGINT from pid 0, uid 0; shutting down...
info: Shutting down client connections...
info: All client connections closed.
info: Shutting down storage engine... (This may take a while if you had a lot of unflushed data
    in the writeback cache.)
info: Storage engine shut down.
error: Forever detected script exited with code: 0
```

Is it possible to run reqlite as a background process?

My goal is to: start reqlite, run a gulp task, stop reqlite.

**Comment by neumino** [comment]
`node lib/node.js`. Make sure that the port are available.

**Comment by chrisabrams** [comment]
@neumino when I run this it seems to always run on port 28015:

```
forever start node_modules/reqlite/lib/node.js --port-offset 1
```

Which should run it on port 28016, but `rethinkdbdash` outputs:

```
Creating a pool connected to 127.0.0.1:28015
```

Even though I set my config for rethinkdbdash to be port 28016.

**Comment by neumino** [comment]
Did you tell rethinkdbdash to connect on port 28016?

**Comment by chrisabrams** [comment]
Yes I did; I don't know what is wrong with my config, but I ran another script connecting to 28016 and things worked fine. Thanks for the help!
