### ISSUE TITLE
`run` was called without a connection and no pool has been created

### ISSUE THREAD

**Issue by nodesocket** [neumino/reqlite#83]
How can I use reqlite without changing how I execute queries? Currently I have:

```
const r = require('rethinkdbdash')({ pool: false });
const Reqlite = require('reqlite');
const rl = new Reqlite();
r.connect({
    connection: rl.createConnection()
});

const data = { foo: 'bar' };
 r.table('events').insert(data).then(() => {
    // more code here
});
```

I am getting an error:

```
`run` was called without a connection and no pool has been created after:\nr.table(\"events\").insert({\n    id: \"fd7db3d8-b53e-49d8-b563-a50b492eb1ca\"\n})"}
```

**Comment by neumino** [comment]
You are executing your query by calling `then` on it, which calls `run` without a connection. You need to pass the connection

```
r.connect({
  connection: rl.createConnection()
}).then(function(connection) {
  return r.table('events').insert(data).run(connection)
})
```

See this file for example:
https://github.com/neumino/reqlite/blob/8609293f629684a37e848bbb7f58a0071011b6b2/browser/example.js

**Comment by nodesocket** [comment]
But that breaks code already in production using `rethinkdbdash` which does not require this syntax. I can simply do:

```
const r = require('rethinkdbdash')({ pool: true });
r.table('events').insert(data).then(() => {
    // more code here
});
```

Is there another way around this without wrapping with `.then(connection)`?

**Comment by neumino** [comment]
You can start reqlite in its own process with `lib/node.js`.

`rethinkdbdash` has been modified to understand mocked TCP connections, but the pool master hasn't been updated to be able to create fake tcp connections

**Comment by nodesocket** [comment]
Can you provide an example of starting `lib/node.js` from inside of JavaScript? Would I just spawn `node_modules/reqlite/lib/node.js`? That seems incredibly hacky and fragile.

**Comment by neumino** [comment]
I don't have a written example but yea, it's just about spawning `node_modules/reqlite/lib/node.js`

**Comment by neumino** [comment]
It's also reasonable to update rethinkdbdash to get a tcp connections factory. It doesn't seem like too much work.

**Comment by nodesocket** [comment]
Ok, I solved this by using a bash script for my test runner and invoking:

```
node node_modules/reqlite/lib/node.js
```
